# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            /home/circleci/repo/venv/bin/python3 -m pip install --upgrade pip
            apt-get install -y libglib2.0-0=2.50.3-2 \
            libnss3=2:3.26.2-1.1+deb9u1 \
            libgconf-2-4=3.2.6-4+b1 \
            libfontconfig1=2.11.0-6.7+b1
            pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            flake8 --exclude=venv* --statistics
            pytest -v --cov