
version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout

      # Step 2: create virtual env and install dependencies
      - python/install-packages:
          pkg-manager: pip

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            /home/circleci/repo/venv/bin/python3 -m pip install --upgrade pip
            pip install -r requirements.txt

      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            flake8 --exclude=venv* --statistics
            pytest -v --cov

workflows:
  build-and-test: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-and-test